"""Add username

Revision ID: 353940057ec1
Revises: c5361e0b1afe
Create Date: 2021-03-13 20:28:48.807490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353940057ec1'
down_revision = 'c5361e0b1afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('users', 'username')
    # this line is only for sqlite
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("username")
    # ### end Alembic commands ###
